#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChungCu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_QuanLyChungCu")]
	public partial class DB_QuanLyChungCuDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCanHo(CanHo instance);
    partial void UpdateCanHo(CanHo instance);
    partial void DeleteCanHo(CanHo instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertCuDan(CuDan instance);
    partial void UpdateCuDan(CuDan instance);
    partial void DeleteCuDan(CuDan instance);
    partial void InsertHopDong(HopDong instance);
    partial void UpdateHopDong(HopDong instance);
    partial void DeleteHopDong(HopDong instance);
    partial void InsertKhuCanHo(KhuCanHo instance);
    partial void UpdateKhuCanHo(KhuCanHo instance);
    partial void DeleteKhuCanHo(KhuCanHo instance);
    #endregion
		
		public DB_QuanLyChungCuDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_QuanLyChungCuConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_QuanLyChungCuDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_QuanLyChungCuDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_QuanLyChungCuDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_QuanLyChungCuDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CanHo> CanHos
		{
			get
			{
				return this.GetTable<CanHo>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<CuDan> CuDans
		{
			get
			{
				return this.GetTable<CuDan>();
			}
		}
		
		public System.Data.Linq.Table<HopDong> HopDongs
		{
			get
			{
				return this.GetTable<HopDong>();
			}
		}
		
		public System.Data.Linq.Table<KhuCanHo> KhuCanHos
		{
			get
			{
				return this.GetTable<KhuCanHo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CanHo")]
	public partial class CanHo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCanHo;
		
		private System.Nullable<double> _DienTich;
		
		private System.Nullable<long> _Gia;
		
		private System.Nullable<bool> _TrangThai;
		
		private System.Nullable<int> _SoPhong;
		
		private string _MaCuDan;
		
		private System.Nullable<int> _MaKhu;
		
		private EntitySet<HopDong> _HopDongs;
		
		private EntityRef<CuDan> _CuDan;
		
		private EntityRef<KhuCanHo> _KhuCanHo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCanHoChanging(string value);
    partial void OnMaCanHoChanged();
    partial void OnDienTichChanging(System.Nullable<double> value);
    partial void OnDienTichChanged();
    partial void OnGiaChanging(System.Nullable<long> value);
    partial void OnGiaChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    partial void OnSoPhongChanging(System.Nullable<int> value);
    partial void OnSoPhongChanged();
    partial void OnMaCuDanChanging(string value);
    partial void OnMaCuDanChanged();
    partial void OnMaKhuChanging(System.Nullable<int> value);
    partial void OnMaKhuChanged();
    #endregion
		
		public CanHo()
		{
			this._HopDongs = new EntitySet<HopDong>(new Action<HopDong>(this.attach_HopDongs), new Action<HopDong>(this.detach_HopDongs));
			this._CuDan = default(EntityRef<CuDan>);
			this._KhuCanHo = default(EntityRef<KhuCanHo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCanHo", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCanHo
		{
			get
			{
				return this._MaCanHo;
			}
			set
			{
				if ((this._MaCanHo != value))
				{
					this.OnMaCanHoChanging(value);
					this.SendPropertyChanging();
					this._MaCanHo = value;
					this.SendPropertyChanged("MaCanHo");
					this.OnMaCanHoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich", DbType="Float")]
		public System.Nullable<double> DienTich
		{
			get
			{
				return this._DienTich;
			}
			set
			{
				if ((this._DienTich != value))
				{
					this.OnDienTichChanging(value);
					this.SendPropertyChanging();
					this._DienTich = value;
					this.SendPropertyChanged("DienTich");
					this.OnDienTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="BigInt")]
		public System.Nullable<long> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhong", DbType="Int")]
		public System.Nullable<int> SoPhong
		{
			get
			{
				return this._SoPhong;
			}
			set
			{
				if ((this._SoPhong != value))
				{
					this.OnSoPhongChanging(value);
					this.SendPropertyChanging();
					this._SoPhong = value;
					this.SendPropertyChanged("SoPhong");
					this.OnSoPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCuDan", DbType="NChar(10)")]
		public string MaCuDan
		{
			get
			{
				return this._MaCuDan;
			}
			set
			{
				if ((this._MaCuDan != value))
				{
					if (this._CuDan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCuDanChanging(value);
					this.SendPropertyChanging();
					this._MaCuDan = value;
					this.SendPropertyChanged("MaCuDan");
					this.OnMaCuDanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhu", DbType="Int")]
		public System.Nullable<int> MaKhu
		{
			get
			{
				return this._MaKhu;
			}
			set
			{
				if ((this._MaKhu != value))
				{
					if (this._KhuCanHo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhuChanging(value);
					this.SendPropertyChanging();
					this._MaKhu = value;
					this.SendPropertyChanged("MaKhu");
					this.OnMaKhuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CanHo_HopDong", Storage="_HopDongs", ThisKey="MaCanHo", OtherKey="MaCanHo")]
		public EntitySet<HopDong> HopDongs
		{
			get
			{
				return this._HopDongs;
			}
			set
			{
				this._HopDongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuDan_CanHo", Storage="_CuDan", ThisKey="MaCuDan", OtherKey="MaCuDan", IsForeignKey=true)]
		public CuDan CuDan
		{
			get
			{
				return this._CuDan.Entity;
			}
			set
			{
				CuDan previousValue = this._CuDan.Entity;
				if (((previousValue != value) 
							|| (this._CuDan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CuDan.Entity = null;
						previousValue.CanHos.Remove(this);
					}
					this._CuDan.Entity = value;
					if ((value != null))
					{
						value.CanHos.Add(this);
						this._MaCuDan = value.MaCuDan;
					}
					else
					{
						this._MaCuDan = default(string);
					}
					this.SendPropertyChanged("CuDan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhuCanHo_CanHo", Storage="_KhuCanHo", ThisKey="MaKhu", OtherKey="MaKhu", IsForeignKey=true)]
		public KhuCanHo KhuCanHo
		{
			get
			{
				return this._KhuCanHo.Entity;
			}
			set
			{
				KhuCanHo previousValue = this._KhuCanHo.Entity;
				if (((previousValue != value) 
							|| (this._KhuCanHo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhuCanHo.Entity = null;
						previousValue.CanHos.Remove(this);
					}
					this._KhuCanHo.Entity = value;
					if ((value != null))
					{
						value.CanHos.Add(this);
						this._MaKhu = value.MaKhu;
					}
					else
					{
						this._MaKhu = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhuCanHo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HopDongs(HopDong entity)
		{
			this.SendPropertyChanging();
			entity.CanHo = this;
		}
		
		private void detach_HopDongs(HopDong entity)
		{
			this.SendPropertyChanging();
			entity.CanHo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenTaiKhoan;
		
		private string _MatKhau;
		
		private System.Nullable<bool> _VaiTro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenTaiKhoanChanging(string value);
    partial void OnTenTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnVaiTroChanging(System.Nullable<bool> value);
    partial void OnVaiTroChanged();
    #endregion
		
		public TaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiKhoan", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenTaiKhoan
		{
			get
			{
				return this._TenTaiKhoan;
			}
			set
			{
				if ((this._TenTaiKhoan != value))
				{
					this.OnTenTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TenTaiKhoan = value;
					this.SendPropertyChanged("TenTaiKhoan");
					this.OnTenTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NChar(20)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VaiTro", DbType="Bit")]
		public System.Nullable<bool> VaiTro
		{
			get
			{
				return this._VaiTro;
			}
			set
			{
				if ((this._VaiTro != value))
				{
					this.OnVaiTroChanging(value);
					this.SendPropertyChanging();
					this._VaiTro = value;
					this.SendPropertyChanged("VaiTro");
					this.OnVaiTroChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CuDan")]
	public partial class CuDan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCuDan;
		
		private string _TenCuDan;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<bool> _GioiTinh;
		
		private string _SoDT;
		
		private string _SoCMT;
		
		private string _QueQuan;
		
		private EntitySet<CanHo> _CanHos;
		
		private EntitySet<HopDong> _HopDongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCuDanChanging(string value);
    partial void OnMaCuDanChanged();
    partial void OnTenCuDanChanging(string value);
    partial void OnTenCuDanChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnSoDTChanging(string value);
    partial void OnSoDTChanged();
    partial void OnSoCMTChanging(string value);
    partial void OnSoCMTChanged();
    partial void OnQueQuanChanging(string value);
    partial void OnQueQuanChanged();
    #endregion
		
		public CuDan()
		{
			this._CanHos = new EntitySet<CanHo>(new Action<CanHo>(this.attach_CanHos), new Action<CanHo>(this.detach_CanHos));
			this._HopDongs = new EntitySet<HopDong>(new Action<HopDong>(this.attach_HopDongs), new Action<HopDong>(this.detach_HopDongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCuDan", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCuDan
		{
			get
			{
				return this._MaCuDan;
			}
			set
			{
				if ((this._MaCuDan != value))
				{
					this.OnMaCuDanChanging(value);
					this.SendPropertyChanging();
					this._MaCuDan = value;
					this.SendPropertyChanged("MaCuDan");
					this.OnMaCuDanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCuDan", DbType="NVarChar(150)")]
		public string TenCuDan
		{
			get
			{
				return this._TenCuDan;
			}
			set
			{
				if ((this._TenCuDan != value))
				{
					this.OnTenCuDanChanging(value);
					this.SendPropertyChanging();
					this._TenCuDan = value;
					this.SendPropertyChanged("TenCuDan");
					this.OnTenCuDanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="NChar(20)")]
		public string SoDT
		{
			get
			{
				return this._SoDT;
			}
			set
			{
				if ((this._SoDT != value))
				{
					this.OnSoDTChanging(value);
					this.SendPropertyChanging();
					this._SoDT = value;
					this.SendPropertyChanged("SoDT");
					this.OnSoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCMT", DbType="NChar(20)")]
		public string SoCMT
		{
			get
			{
				return this._SoCMT;
			}
			set
			{
				if ((this._SoCMT != value))
				{
					this.OnSoCMTChanging(value);
					this.SendPropertyChanging();
					this._SoCMT = value;
					this.SendPropertyChanged("SoCMT");
					this.OnSoCMTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueQuan", DbType="NVarChar(250)")]
		public string QueQuan
		{
			get
			{
				return this._QueQuan;
			}
			set
			{
				if ((this._QueQuan != value))
				{
					this.OnQueQuanChanging(value);
					this.SendPropertyChanging();
					this._QueQuan = value;
					this.SendPropertyChanged("QueQuan");
					this.OnQueQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuDan_CanHo", Storage="_CanHos", ThisKey="MaCuDan", OtherKey="MaCuDan")]
		public EntitySet<CanHo> CanHos
		{
			get
			{
				return this._CanHos;
			}
			set
			{
				this._CanHos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuDan_HopDong", Storage="_HopDongs", ThisKey="MaCuDan", OtherKey="MaCuDan")]
		public EntitySet<HopDong> HopDongs
		{
			get
			{
				return this._HopDongs;
			}
			set
			{
				this._HopDongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CanHos(CanHo entity)
		{
			this.SendPropertyChanging();
			entity.CuDan = this;
		}
		
		private void detach_CanHos(CanHo entity)
		{
			this.SendPropertyChanging();
			entity.CuDan = null;
		}
		
		private void attach_HopDongs(HopDong entity)
		{
			this.SendPropertyChanging();
			entity.CuDan = this;
		}
		
		private void detach_HopDongs(HopDong entity)
		{
			this.SendPropertyChanging();
			entity.CuDan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HopDong")]
	public partial class HopDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHopDong;
		
		private System.Nullable<System.DateTime> _NgayGiaoDich;
		
		private string _MaCanHo;
		
		private string _MaCuDan;
		
		private EntityRef<CanHo> _CanHo;
		
		private EntityRef<CuDan> _CuDan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHopDongChanging(string value);
    partial void OnMaHopDongChanged();
    partial void OnNgayGiaoDichChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGiaoDichChanged();
    partial void OnMaCanHoChanging(string value);
    partial void OnMaCanHoChanged();
    partial void OnMaCuDanChanging(string value);
    partial void OnMaCuDanChanged();
    #endregion
		
		public HopDong()
		{
			this._CanHo = default(EntityRef<CanHo>);
			this._CuDan = default(EntityRef<CuDan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					this.OnMaHopDongChanging(value);
					this.SendPropertyChanging();
					this._MaHopDong = value;
					this.SendPropertyChanged("MaHopDong");
					this.OnMaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiaoDich", DbType="Date")]
		public System.Nullable<System.DateTime> NgayGiaoDich
		{
			get
			{
				return this._NgayGiaoDich;
			}
			set
			{
				if ((this._NgayGiaoDich != value))
				{
					this.OnNgayGiaoDichChanging(value);
					this.SendPropertyChanging();
					this._NgayGiaoDich = value;
					this.SendPropertyChanged("NgayGiaoDich");
					this.OnNgayGiaoDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCanHo", DbType="NChar(10)")]
		public string MaCanHo
		{
			get
			{
				return this._MaCanHo;
			}
			set
			{
				if ((this._MaCanHo != value))
				{
					if (this._CanHo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCanHoChanging(value);
					this.SendPropertyChanging();
					this._MaCanHo = value;
					this.SendPropertyChanged("MaCanHo");
					this.OnMaCanHoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCuDan", DbType="NChar(10)")]
		public string MaCuDan
		{
			get
			{
				return this._MaCuDan;
			}
			set
			{
				if ((this._MaCuDan != value))
				{
					if (this._CuDan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCuDanChanging(value);
					this.SendPropertyChanging();
					this._MaCuDan = value;
					this.SendPropertyChanged("MaCuDan");
					this.OnMaCuDanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CanHo_HopDong", Storage="_CanHo", ThisKey="MaCanHo", OtherKey="MaCanHo", IsForeignKey=true)]
		public CanHo CanHo
		{
			get
			{
				return this._CanHo.Entity;
			}
			set
			{
				CanHo previousValue = this._CanHo.Entity;
				if (((previousValue != value) 
							|| (this._CanHo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CanHo.Entity = null;
						previousValue.HopDongs.Remove(this);
					}
					this._CanHo.Entity = value;
					if ((value != null))
					{
						value.HopDongs.Add(this);
						this._MaCanHo = value.MaCanHo;
					}
					else
					{
						this._MaCanHo = default(string);
					}
					this.SendPropertyChanged("CanHo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuDan_HopDong", Storage="_CuDan", ThisKey="MaCuDan", OtherKey="MaCuDan", IsForeignKey=true)]
		public CuDan CuDan
		{
			get
			{
				return this._CuDan.Entity;
			}
			set
			{
				CuDan previousValue = this._CuDan.Entity;
				if (((previousValue != value) 
							|| (this._CuDan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CuDan.Entity = null;
						previousValue.HopDongs.Remove(this);
					}
					this._CuDan.Entity = value;
					if ((value != null))
					{
						value.HopDongs.Add(this);
						this._MaCuDan = value.MaCuDan;
					}
					else
					{
						this._MaCuDan = default(string);
					}
					this.SendPropertyChanged("CuDan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhuCanHo")]
	public partial class KhuCanHo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKhu;
		
		private string _TenKhu;
		
		private System.Nullable<int> _SoTang;
		
		private System.Nullable<int> _SoCanHo;
		
		private string _DiaChi;
		
		private EntitySet<CanHo> _CanHos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhuChanging(int value);
    partial void OnMaKhuChanged();
    partial void OnTenKhuChanging(string value);
    partial void OnTenKhuChanged();
    partial void OnSoTangChanging(System.Nullable<int> value);
    partial void OnSoTangChanged();
    partial void OnSoCanHoChanging(System.Nullable<int> value);
    partial void OnSoCanHoChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public KhuCanHo()
		{
			this._CanHos = new EntitySet<CanHo>(new Action<CanHo>(this.attach_CanHos), new Action<CanHo>(this.detach_CanHos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKhu
		{
			get
			{
				return this._MaKhu;
			}
			set
			{
				if ((this._MaKhu != value))
				{
					this.OnMaKhuChanging(value);
					this.SendPropertyChanging();
					this._MaKhu = value;
					this.SendPropertyChanged("MaKhu");
					this.OnMaKhuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhu", DbType="NVarChar(150)")]
		public string TenKhu
		{
			get
			{
				return this._TenKhu;
			}
			set
			{
				if ((this._TenKhu != value))
				{
					this.OnTenKhuChanging(value);
					this.SendPropertyChanging();
					this._TenKhu = value;
					this.SendPropertyChanged("TenKhu");
					this.OnTenKhuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTang", DbType="Int")]
		public System.Nullable<int> SoTang
		{
			get
			{
				return this._SoTang;
			}
			set
			{
				if ((this._SoTang != value))
				{
					this.OnSoTangChanging(value);
					this.SendPropertyChanging();
					this._SoTang = value;
					this.SendPropertyChanged("SoTang");
					this.OnSoTangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCanHo", DbType="Int")]
		public System.Nullable<int> SoCanHo
		{
			get
			{
				return this._SoCanHo;
			}
			set
			{
				if ((this._SoCanHo != value))
				{
					this.OnSoCanHoChanging(value);
					this.SendPropertyChanging();
					this._SoCanHo = value;
					this.SendPropertyChanged("SoCanHo");
					this.OnSoCanHoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(250)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhuCanHo_CanHo", Storage="_CanHos", ThisKey="MaKhu", OtherKey="MaKhu")]
		public EntitySet<CanHo> CanHos
		{
			get
			{
				return this._CanHos;
			}
			set
			{
				this._CanHos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CanHos(CanHo entity)
		{
			this.SendPropertyChanging();
			entity.KhuCanHo = this;
		}
		
		private void detach_CanHos(CanHo entity)
		{
			this.SendPropertyChanging();
			entity.KhuCanHo = null;
		}
	}
}
#pragma warning restore 1591
